/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnoGDJNUtexM2VTxWUykUyxvjqvBK1DCc',
    appId: '1:992386469400:web:ca6862b2791c5f38f7bd6d',
    messagingSenderId: '992386469400',
    projectId: 'voyage2-a44a4',
    authDomain: 'voyage2-a44a4.firebaseapp.com',
    storageBucket: 'voyage2-a44a4.appspot.com',
    measurementId: 'G-9LYS799C84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5Zj71iNe29SLRCsVgVQEG205_LDdAMo',
    appId: '1:992386469400:android:99b327995aac8341f7bd6d',
    messagingSenderId: '992386469400',
    projectId: 'voyage2-a44a4',
    storageBucket: 'voyage2-a44a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_k4OUuP01w83_Kf5A3rfJ5GiQ2rPScWk',
    appId: '1:992386469400:ios:bc1c9ba6d8db90c5f7bd6d',
    messagingSenderId: '992386469400',
    projectId: 'voyage2-a44a4',
    storageBucket: 'voyage2-a44a4.appspot.com',
    iosClientId: '992386469400-kidmaen2b5ahnio73rler8rmssboocul.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_k4OUuP01w83_Kf5A3rfJ5GiQ2rPScWk',
    appId: '1:992386469400:ios:bc1c9ba6d8db90c5f7bd6d',
    messagingSenderId: '992386469400',
    projectId: 'voyage2-a44a4',
    storageBucket: 'voyage2-a44a4.appspot.com',
    iosClientId: '992386469400-kidmaen2b5ahnio73rler8rmssboocul.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage2',
  );
}
*/